### ISSUE TITLE
Button Hover Not Specified

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/responsive-image-section#1]
@thomasjbradley 

The video (https://www.youtube.com/watch?v=G4904HhFmLQ&feature=youtu.be) didn't show a hover colour for the button, and I couldn't find anything in the screenshots or README file, so I just assigned one. I hope that's okay!

**Comment by thomasjbradley** [comment]
Yep, that’s perfect. I would have done something almost exactly the same.
